version: '3'
services:
  db:
    image: "postgres:9.6.5"
    volumes:
      - ./db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - "dbdata:/var/lib/postgresql/data"
    env_file:
     - env_file
    networks:
      - db_network
  loanapp:
    build: .
    env_file:
      - env_file
    volumes:
      - .:/opt/services/loanapp/src
    networks:
      - db_network
    depends_on:
      - db
networks:
  db_network:
    driver: bridge
volumes:
  dbdata: